apiVersion: v1
kind: Service
metadata:
  name: mysql-public
spec:
  ports:
  - port: 3306 
    name: mysql 
  clusterIP: None
  selector:
    app: mysql-public


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-public
spec:
  serviceName: "mysql-public"
  replicas: 2
  selector:
    matchLabels:
      app: mysql-public
  template:
    metadata:
      labels:
        app: mysql-public
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-public
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-public
        persistentVolumeClaim:
          claimName: mysql-claim

